version: "3.9"

services:

    nginx:
        image: nginx:1.23.3-alpine
        container_name: ${PROJECT_NAME}_nginx
        ports:
          - ${NGINX_PORT}:80
          - ${NGINX_PORT_S}:443
        volumes:
          - ./sites:/var/www
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./nginx/logs:/var/log/nginx/
        depends_on:
          - php
          - postgres
        environment:
          TZ: ${WORKSPACE_TIMEZONE}

    php:
        build:
          context: ./
          dockerfile: ./.docker/php-8.2/Dockerfile
          args:
            - USER_ID
            - GROUP_ID
        container_name: ${PROJECT_NAME}_php-8.2
        ports:
          - ${PHP_PORT}:9000
        working_dir: /var/www
        volumes:
          - ./.ssh:/home/www-data/.ssh
          - ./sites:/var/www
          - ./.docker/php-8.2/php.ini:/usr/local/etc/php/php.ini
        depends_on:
          - postgres

    postgres:
        image: postgres:15.2-alpine
        container_name: ${PROJECT_NAME}_postgres
        volumes:
          - ./postgres/data:/var/lib/postgresql/data
          - ./postgres/dump:/dump
        ports:
          - ${POSTGRES_PORT}:5432
        restart: unless-stopped
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
